### ISSUE TITLE
Some apps cannot be displayed on “App” 

### ISSUE THREAD

**Issue by xmasrain** [SeydX/homebridge-bravia-tvos#124]
“云视听极光”app  cannot be displayed on “App” ，even if I input the app into the line。
![tvos](https://user-images.githubusercontent.com/58833842/103185820-030a5f00-48f9-11eb-80bd-03ec8732b0b9.png)

![IMG_0512](https://user-images.githubusercontent.com/58833842/103185846-28976880-48f9-11eb-98f3-50d2be63e4dc.PNG)

**Comment by SeydX** [comment]
@xmasrain 

interesting. I think the special chars are causing this problem. Will check this. Thanks.

**Comment by SeydX** [comment]
v5.0.0 is online.

Closing this issue because its related to v4.x. Feel free to open/reopen if the issue still exists on v5.

Please read the [changelog](https://github.com/SeydX/homebridge-bravia-tvos/blob/master/Changelog.md#v500---2021-07-04) on how to migrate to v5

**Comment by SeydX** [comment]
Version 5 allows the user to define own names for inputs which should fix this issue

**Comment by QiuYueBaiJXW** [comment]
The bug is still here, I choose the identifier of the apps and click save, the bridge restarted then the identifier is empty! NO APPS shown in the home app!
