### ISSUE TITLE
No identifiers available

### ISSUE THREAD

**Issue by mkoxyz** [SeydX/homebridge-bravia-tvos#160]
As far as I understood the identifiers (TV inputs, Applications) are automatically available after adding new TV.
I also can see that the plugin downloads all the data from the TV but there is no drop down menu where I can select them.
![2635E57F-5B73-4DEB-A085-168C9ACB9D8F](https://user-images.githubusercontent.com/50030931/131211537-2bebb02e-9cd9-4036-aa38-b312513b9d23.jpeg)
My trials to fix this issues:
- TV deleted in the plugin and set up again
- Plugin deleted and restored
- Refreshing the data in the plugin
All this does not help - any ideas?
Homebridge version is 1.3.4 - plugin 5.0.1

**Comment by SeydX** [comment]
Can u try again with v5.0.2 pls

**Comment by SeydX** [comment]
Fixed in v5.0.5

**Comment by mkoxyz** [comment]
Sorry to give so late some feedback but I was on vacation. Well tried 5.0.6 and still the same issue - no identifiers. 
1. Refreshing of the 'old' config. All the data were downloaded but still the same problem
2. Deleting the 'old' config and creating new TV - also here the data is downloaded and stored but not identifiers at all later

**Comment by SeydX** [comment]
Can you post your tv cache (located in your homebridge folder/bravia/TVNAME.json)

And how do you „edit“ your config?

![C81A286F-EB9F-4B86-A9A3-7C41DE25C366](https://user-images.githubusercontent.com/34152761/134815268-6aef2374-20dd-4e2c-8cc3-c79612e386ac.jpeg)

Because there are two possibilities to edit the config. (1) or (2)

**Comment by mkoxyz** [comment]
![image](https://user-images.githubusercontent.com/50030931/134816094-6d6c6400-67b1-4390-85f2-ee50de9f28ac.png)
This is how the file looks like. 
I use the option 2 for editing - is it the right way?

**Comment by mkoxyz** [comment]
Sorry - I use the option 1 for editing.
If I choose the option 2 something like this happens
![image](https://user-images.githubusercontent.com/50030931/134816208-2cc102c0-bac9-4386-8c07-f672c313c5c7.jpeg)

**Comment by SeydX** [comment]
> Sorry - I use the option 1 for editing.
> If I choose the option 2 something like this happens
> ![image](https://user-images.githubusercontent.com/50030931/134816208-2cc102c0-bac9-4386-8c07-f672c313c5c7.jpeg)

Ok thats related to #163 

can you check the error in the browser console pls? And which browser do you use?

anything in the homebridge logs?

**Comment by mkoxyz** [comment]
Well I can not see any errors in the console. Everything seems to work fine - there are also no errors or warnings in the log.
I primarily use Safari (iOS 15) but just checked Edge (one iOS) with the same result - empty page.

**Comment by SeydX** [comment]
Can you remove the browser cache and try again pls

**Comment by mkoxyz** [comment]
No change at all.
I tired also Firefox on my MacBook - the same result.

**Comment by SeydX** [comment]
Can you post your config.json pls

**Comment by mkoxyz** [comment]
{
    "bridge": {
        "name": "Homebridge 5AF8",
        "username": "*********",
        "port": *****,
        "pin": "*********",
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "name": "Nepomuk",
            "model": "600",
            "blid": "*********",
            "robotpwd": "**********",
            "ipaddress": "192.168..",
            "autoRefreshEnabled": true,
            "dockContactSensor": true,
            "runningContactSensor": false,
            "binContactSensor": true,
            "cacheTTL": 900,
            "accessory": "Roomba2"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168..",
            "subsection": "Homekit",
            "enable_hmip": false,
            "enable_wired": false,
            "ios10": true,
            "platform": "HomeMatic"
        },
        {
            "name": "Shelly",
            "admin": {
                "enabled": true
            },
            "requestTimeout": 3000,
            "platform": "Shelly"
        },
        {
            "username": "******",
            "password": "******",
            "enableDetailedLogging": false,
            "pollingIntervalMinutes": "1",
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "hkDisarmed": 6,
            "platform": "EufySecurity",
            "ignoreStations": [],
            "ignoreDevices": []
        },
        {
            "name": "BraviaTVOS",
            "platform": "BraviaOSPlatform",
            "debug": true,
            "warn": true,
            "error": true,
            "extendedError": true,
            "tvs": [
                {
                    "active": true,
                    "name": "Bravia",
                    "ip": "192.168..",
                    "port": 80,
                    "manufacturer": "Sony",
                    "model": "Bravia",
                    "serialNumber": "00000000",
                    "wol": false,
                    "oldModel": false,
                    "refreshInputs": false,
                    "polling": 10,
                    "sheduledRefresh": 12,
                    "inputs": [],
                    "apps": [],
                    "channels": [],
                    "commands": [],
                    "macros": [],
                    "remote": [],
                    "displayOrder": [
                        "inputs",
                        "apps",
                        "channels",
                        "commands",
                        "macros"
                    ],
                    "speaker": {
                        "active": true,
                        "output": "speaker",
                        "increaseBy": 1,
                        "reduceBy": 1,
                        "accType": "lightbulb"
                    },
                    "psk": "********"
                }
            ]
        }
    ],
    "disabledPlugins": [
        "homebridge-plugin-eufy-security"
    ]
}

**Comment by SeydX** [comment]
can u test v5.0.7-beta pls

`sudo npm i -g homebridge-bravia-tvos@beta`

Closing this issue, because its the same with #163

**Comment by mkoxyz** [comment]
Both, the 5.0.7 beta as well the released 5.0.7 show the same behavior:
- no identifiers if you use the "upper" config link
- blank page if you try to config the TV by using the "lower" config button

Steps done
- installing 5.0.7
- deleting "old" TV
- restarting the whole homebodies server
- setting up new TV

**Comment by SeydX** [comment]
The „upper“ config is an advanced form of config which provides the user to put inputs which cant be cached from the plugin. So It is intended that it does not show any inputs.

User which can not handle that should use the „lower“ config.

pls try following steps:

1. Remove the tv cache (homebridge folder/bravia/TVNAME.json
2. Open config ui and „refresh“ the tv cache on selecting the tv and clicking he refresh button
3. Try to open the tv config (lower config)

**Comment by mkoxyz** [comment]
After following your instructions there is still an empty config page.
After deleting and reinstalling the plugin there is still the same problem

**Comment by SeydX** [comment]
@mkoxyz 

can u post the tv cache here and the browser console

**Comment by mkoxyz** [comment]
> @mkoxyz 
> 
> 
> 
> can u post the tv cache here and the browser console 

Which files exactly do you need?

**Comment by SeydX** [comment]
you can use online tools like https://ctxt.io/ for copy paste your cache

**Comment by SeydX** [comment]
Your tv cache looks normal. Can you post me your browser console please?

1. Open `Google Chrome`
2. Open `Homebridge UI`
3. Switch to `Plugins`
4. Open Google `DevTools` (Windows: `CTRL+ SHIFT + I` - Mac: `Cmd + Option + I`)
5. In `DevTools` switch tab to `Console`
6. In `Homebridge UI > Plugins`, select Bravia TV OS `Settings`
7. Select your TV
8. Click on the purple `Edit Icon`
9. Make a screenshot from your DevTools Console and post it here pls

**Comment by mkoxyz** [comment]
This is how the screenshot looks like
![image](https://user-images.githubusercontent.com/50030931/136619490-72bcf9e9-b818-4c40-b084-920985b6d92a.png)

I just noticed that the ONLY combination where this page opens correctly is my iMac and Chrome. Any other browser on iMac opened only the blank page. On my iPad/iPhone the page opens only blank - no matter which browser I use
