### ISSUE TITLE
Unable to set up 4.1 using new UI

### ISSUE THREAD

**Issue by Fofer** [SeydX/homebridge-bravia-tvos#99]
The new setup UI looks great! But it's not working for me, I get stuck on this screen, the gear just turns and turns.

![CleanShot 2020-11-21 at 22 12 02](https://user-images.githubusercontent.com/518749/99896585-c175fc80-2c46-11eb-8b6b-05f0335a469d.png)

I am running Homebridge 1.1.6, Node.js v14.15.1, and Npm v6.14.8.  I have 11 other plug-ins installed, all working fine.

The error in my homebridge logs says this:

```
 [21/11/2020, 22:11:02] [Homebridge UI] [homebridge-bravia-tvos] internal/modules/cjs/loader.js:883
  throw err;
  ^Error: Cannot find module '@homebridge/plugin-ui-utils'
Require stack:
- /usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:1:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js'
  ]
}

```

Any pointers appreciated!

**Comment by SeydX** [comment]
@Fofer 

Aah sry, forgotten to add plugin ui utils as dependency 😑

Should be fixed with v4.1.1

**Comment by Fofer** [comment]
Thanks for the quick reply!  I just updated to 4.1.1 and it's still not working.  Now the gear goes away but the setup window stays blank.

![CleanShot 2020-11-21 at 23 07 53](https://user-images.githubusercontent.com/518749/99897472-a14a3b80-2c4e-11eb-89e4-d8fa1e77f973.png)

I uninstalled and reinstalled the plugin, I rebooted Homebridge, and I also reboot the Raspberry Pi, all to no avail.  The error logs only say this:

`[21/11/2020, 23:08:37] [Homebridge UI] [homebridge-bravia-tvos] Terminating child process...
[21/11/2020, 23:08:37] [Homebridge UI] [homebridge-bravia-tvos] Child process ended`

**Comment by SeydX** [comment]
@Fofer 

Config ui x version?

**Comment by Fofer** [comment]
@SeydX 

homebridge-config-ui-x v4.34.0

**Comment by SeydX** [comment]
@Fofer 

Anything in the browser debugging console?

**Comment by Fofer** [comment]
This is what I see in the javascript console:

![CleanShot 2020-11-22 at 05 44 16](https://user-images.githubusercontent.com/518749/99905486-e2aa0d80-2c85-11eb-95a0-527eb40cfede.png)

**Comment by SeydX** [comment]
@Fofer 

can u try reinstalling the plugin pls?

``sudo npm i -g homebridge-bravia-tvos@latest --unsafe-perm``

**Comment by Fofer** [comment]
I tried that, and restarted homebridge, and am still unable to access the new setup UI via this laptop.
I get the same frozen blank screen.
However, I've figured out a big clue.  It DOES work in Safari on my iPhone running iOS 14.2.  It also works in Google Chrome v86.0.4240.198.
Where it doesn't work is my MacBook Pro, running Safari 12.1.2 and macOS Mojave 10.14.6.  (I need to keep this particular machine on this older version for now.)
So I'm able to handle the new configuration so long as I use another browser / device.
Hopefully this is helpful information or you and other potential users.

As an aside, "Catagory" under "Display Order" should be spelled "Cat**e**gory."

Thank you for all the help and attention, and for sharing your work on this great plugin.

**Comment by SeydX** [comment]
Ahh, ok. I forwarded this to oznu (developer of config-ui-x)

thx

**Comment by Fofer** [comment]
No problem, hopefully oznu can help. 

 I will note that I've had no other issues with config-ui-x on this laptop, everything has worked brilliantly. This is the first homebridge plugin that's posed a problem.  

Perhaps you can introduce a failsafe mechanism, if the new setup wizard doesn't work, the user could click a button to revert to the older "manual" method? (which worked fine for me too.)

Anyway, thanks for the great plugin, your work is greatly appreciated.

**Comment by SeydX** [comment]
@Fofer 

There is already a fallback for user with homebridge-config-ui-x  < v4.34.0

Already tried a another plugin with custom ui support?

Maybe you could install, just for testing purposes, **homebridge-electra-smart** or **homebridge-gsh** which also supports custom ui

**Comment by Fofer** [comment]
I did some testing as you requested.

For starters, this homebridge-bravia-tvos plugin **does** work in Safari 13.2, just not the older version of Safari 12.1.2 I use as my default browser.  (I was able to test version 13.2 by way of the "Safari Technology Preview" I have installed as an alternate browser.)

It also works in Google Chrome and presumably, the current Safari 14.

The same goes for homebridge-electra-smart.  Same exact issue.

However, homebridge-gsh works fine in all browsers I tried, even Safari 12.1.2.

Perhaps for older browser versions there can be a fallback as well?  Or at the very least, explanatory text that says "if this screen remains blank, try a newer browser." ;)

**Comment by SeydX** [comment]
I talked to oznu about it and the new custom ui is only compatible with iOS 14 and two most recent major versions of Safari/Chrome/Firefox Browser

https://github.com/oznu/homebridge-config-ui-x#supported-browsers

**Comment by oznu** [comment]
A fix for older browsers is now in the `@test` tag of the Homebridge UI.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by Fofer** [comment]
Hi, this has been addressed in homebridge-config-ui-x v4.35.0

"Plugins: Custom plugin user interfaces now work correctly in older browsers that do not support the EventTarget constructor."
